#!/usr/bin/env python3
"""Pre-build every particle stamp routine Func_ed408 can generate.

Func_ed408 (ROM 0x080ED408) writes an ARM routine into a heap block. Its
output depends only on r1, r2 (log2 canvas sizes), r3 (4 flag bits) and the
mode argument (0..3), and every branch in it is relative, so the same bytes
run at any address (FACTS.md, 2026-09-23). This script:

1. runs the ROM's own builder under Unicorn for every input combination
   (tools/emulate_stamp_builder.py),
2. packs the distinct routines into one binary at ORIGIN, 4-byte aligned,
3. writes a gba_recompile config for it (one entry and one resume range per
   routine) and a registry (stamp_registry.cpp: offset, length and SHA-1 of
   each routine) that the runner uses to recognise a live stamp,
4. with --recompile, runs gba_recompile as a position-independent image.

Output goes to --out-dir (default local/gs011/stamps).
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path

from emulate_stamp_builder import EXPECTED_ROM_SHA1, run

ORIGIN = 0x02000000
SIZES = (7, 8)          # log2 canvas width/height: 128 seen, 256 by one caller
FLAGS = range(16)
MODES = range(4)
PREFIX = "gsr_stamps_"


def build(rom: bytes) -> list[dict]:
    seen: dict[bytes, dict] = {}
    for width in SIZES:
        for height in SIZES:
            for flags in FLAGS:
                for mode in MODES:
                    iwram = run(rom, 0, width, height, flags, mode, 0x03006000)
                    image = iwram[0x6000:0x6800].rstrip(b"\0")
                    if len(image) % 4:
                        image += b"\0" * (4 - len(image) % 4)
                    if image not in seen:
                        seen[image] = {
                            "bytes": image,
                            "inputs": [(width, height, flags, mode)],
                        }
                    else:
                        seen[image]["inputs"].append((width, height, flags, mode))
    variants = list(seen.values())
    offset = 0
    for variant in variants:
        variant["offset"] = offset
        variant["length"] = len(variant["bytes"])
        variant["sha1"] = hashlib.sha1(variant["bytes"]).hexdigest()
        offset += variant["length"]
    return variants


def render_config(variants: list[dict], image_sha1: str, size: int) -> str:
    lines = [
        "# Private generated input; do not commit. tools/build_stamp_variants.py",
        "# Every routine Func_ed408 can build, packed at a generation origin.",
        "[program]",
        'name = "Golden Sun particle stamp routines"',
        'id = "golden_sun_usa_stamps"',
        f"load_address = 0x{ORIGIN:08x}",
        f"size = 0x{size:08x}",
        f"entry_pc = 0x{ORIGIN:08x}",
        "speculative_literal_harvest = false",
        "codegen_shards = 4",
        "",
        "[identity]",
        f'sha1 = "{image_sha1}"',
    ]
    for index, variant in enumerate(variants):
        start = ORIGIN + variant["offset"]
        end = start + variant["length"]
        w, h, f, m = variant["inputs"][0]
        lines += [
            "",
            "[[extra_func]]",
            f"addr = 0x{start:08x}",
            'mode = "arm"',
            f'name = "stamp_{index:03d}"',
            f'note = "Func_ed408 output for r1={w} r2={h} r3={f} mode={m} '
            f'and {len(variant["inputs"]) - 1} other input(s)"',
            "",
            "[[resume_range]]",
            f"start = 0x{start:08x}",
            f"end = 0x{end:08x}",
            'mode = "arm"',
            'note = "whole routine; every instruction is an entry"',
        ]
    return "\n".join(lines) + "\n"


def render_registry(variants: list[dict]) -> str:
    rows = "\n".join(
        f'    {{0x{v["offset"]:05X}u, 0x{v["length"]:03X}u, "{v["sha1"]}"}},'
        for v in variants
    )
    return f"""// AUTO-GENERATED by tools/build_stamp_variants.py. DO NOT EDIT.
// Func_ed408 stamp routines packed at 0x{ORIGIN:08X}; offsets are from the
// image origin, lengths in bytes, SHA-1 over the routine's bytes.
#include <cstdint>

struct GsrStampVariant {{
    std::uint32_t offset;
    std::uint32_t length;
    const char* sha1;
}};

extern "C" const GsrStampVariant {PREFIX}kVariants[] = {{
{rows}
}};
extern "C" const unsigned {PREFIX}kVariantCount = {len(variants)}u;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rom", required=True, type=Path)
    parser.add_argument("--out-dir", type=Path, default=Path("local/gs011/stamps"))
    parser.add_argument("--stage-dir", type=Path, required=True,
                        help="where the packed binary and config are written")
    parser.add_argument("--recompile", type=Path,
                        help="gba_recompile.exe; runs it when given")
    args = parser.parse_args()

    rom = args.rom.read_bytes()
    if hashlib.sha1(rom).hexdigest() != EXPECTED_ROM_SHA1:
        raise SystemExit("unsupported ROM")
    variants = build(rom)
    image = b"".join(v["bytes"] for v in variants)
    image_sha1 = hashlib.sha1(image).hexdigest()

    args.stage_dir.mkdir(parents=True, exist_ok=True)
    binary = args.stage_dir / "stamps.bin"
    config = args.stage_dir / "stamps.toml"
    binary.write_bytes(image)
    config.write_text(render_config(variants, image_sha1, len(image)),
                      encoding="utf-8", newline="\n")
    print(f"variants={len(variants)} bytes={len(image)} sha1={image_sha1}")

    if args.recompile:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        log = args.stage_dir / "recompile.log"
        with log.open("w", encoding="utf-8") as out:
            subprocess.run(
                [
                    str(args.recompile),
                    "--rom", str(binary),
                    "--rom-base", f"0x{ORIGIN:08X}",
                    "--config", str(config),
                    "--out", str(args.out_dir),
                    "--symbol-prefix", PREFIX,
                    "--relocatable-image", f"0x{ORIGIN:08X}:0x{len(image):X}",
                ],
                check=True, stdout=out, stderr=subprocess.STDOUT,
            )
        (args.out_dir / "stamp_registry.cpp").write_text(
            render_registry(variants), encoding="utf-8", newline="\n")
        print(f"corpus={args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
